name: bitmovin_player_example
description: Demonstrates how to use the Bitmovin Player Flutter SDK.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '^3.0.0'

dependencies:
  audio_session: ^0.2.2
  bitmovin_player:
    path: ../
  cupertino_icons: ^1.0.2
  envied: ^1.0.0
  flutter:
    sdk: flutter
  logger: ^2.0.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  player_testing:
    path: ../player_testing
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
