name: bitmovin_player
description: A flutter plugin for Bitmovin Player
version: 0.0.1
homepage: https://bitmovin.com

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  dartdoc: ^6.2.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_easylogger: ^2.3.3
  json_annotation: ^4.8.0
  logger: ^1.3.0
  plugin_platform_interface: ^2.0.2
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.bitmovin.player.flutter
        pluginClass: PlayerPlugin
      ios:
        pluginClass: PlayerPlugin