name: bitmovin_player
description: Official Flutter bindings for Bitmovin's mobile Player SDKs.
version: 0.15.0
homepage: https://bitmovin.com
repository: https://github.com/bitmovin/bitmovin-player-flutter
issue_tracker: https://github.com/bitmovin/bitmovin-player-flutter/issues
documentation: https://developer.bitmovin.com/playback/docs/overview-flutter
topics:
  - video
  - player
  - video-player
  - livestream

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.1
  json_annotation: ^4.9.0
  logger: ^2.0.2
  plugin_platform_interface: ^2.0.2
  uuid: ^4.0.0
  # If web 1.0.0+ is used, it requires Dart ^3.4.0
  web: '>=0.5.0 <2.0.0'

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ">=0.5.2 <2.0.0"
  flutter_lints: ">=3.0.1 <6.0.0"
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  very_good_analysis: ">=5.1.0 <8.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.bitmovin.player.flutter
        pluginClass: PlayerPlugin
      ios:
        pluginClass: PlayerPlugin
      web:
        pluginClass: BitmovinPlayerPlatformWeb
        fileName: src/platform/web/bitmovin_player_platform_web.dart
