name: bitmovin_player
description: Official Flutter bindings for Bitmovin's mobile Player SDKs.
version: 0.4.0
homepage: https://bitmovin.com
repository: https://github.com/bitmovin/bitmovin-player-flutter
issue_tracker: https://github.com/bitmovin/bitmovin-player-flutter/issues
documentation: https://developer.bitmovin.com/playback/docs/overview-flutter
topics:
  - video
  - player
  - video-player
  - livestream

environment:
  sdk: '>=2.19.1 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  logger: ^2.0.2
  plugin_platform_interface: ^2.0.2
  uuid: ^4.0.0

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.5.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.bitmovin.player.flutter
        pluginClass: PlayerPlugin
      ios:
        pluginClass: PlayerPlugin
