name: player_testing
description: Player integration testing library
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0-245.0.dev <4.0.0'

# Add regular dependencies here.
dependencies:
  bitmovin_player:
    path: ../
  envied: ^0.3.0+3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^4.0.0
