name: player_testing
description: Player integration testing library
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '^3.5.0'

dependencies:
  bitmovin_player:
    path: ../
  collection: ^1.17.1
  envied: ^1.0.0
  logger: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^1.0.0
  lints: ^6.0.0
  test: ^1.21.0
  very_good_analysis: ^9.0.0
