name: player_testing
description: Player integration testing library
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0-245.0.dev <4.0.0'

dependencies:
  bitmovin_player:
    path: ../
  collection: ^1.17.1
  envied: ^0.3.0+3
  logger: ^2.0.2

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0+3
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.1.0
