name: Generate documentation
on:
  workflow_dispatch:
jobs:
  generate-documentation:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0
      - name: Install dependencies
        run: dart pub get
      - name: Analyze project source
        run: dart analyze
      - name: Generate documentation
        run: dart doc .
