name: Generate documentation
on:
  workflow_dispatch:
jobs:
  generate-documentation:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Flutter environment
        uses: subosito/flutter-action@v2
      # TODO: Turn this into an action. Maybe also include flutter-action@v2 there
      - name: Create env file
        run: |
          touch .env
          echo BITMOVIN_PLAYER_LICENSE_KEY=_unset_ >> .env
          echo BITMOVIN_ANALYTICS_LICENSE_KEY=_unset_ >> .env
      - name: Generate missing part files
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze project source
        run: flutter analyze
      - name: Generate documentation
        run: dart doc .
      # TODO: upload doc to CDN
